### ISSUE TITLE
iOS 12 上旋转到横屏后，状态栏消失。

### ISSUE THREAD

**Issue by Korune** [yhl714387953/ScreenRotate#1]
你好，iOS 12 上旋转到横屏后，状态栏消失。如下图：
![image](https://user-images.githubusercontent.com/26709394/62850231-cb574300-bd14-11e9-95a9-7f8c20856c9e.png)

**Comment by yhl714387953** [comment]
在iPhone X以上的设备确实不显示，需要实现下面的方法，有导航栏就在导航控制器里实现：
-(void)setNeedsStatusBarAppearanceUpdate {
    NSLog(@"---实现这个方法就能在iPhone X以上的设备显示了---");
}
感谢兄弟

**Comment by Korune** [comment]
^_^
